### ISSUE TITLE
`queryAll` optimization

### ISSUE THREAD

**Issue by dy** [josh/selector-set#30]
`queryAll` can do better than https://github.com/josh/selector-set/blob/master/selector-set.next.js#L377:
instead of selecting all elements matching all rules in context, individual selectors may have up to 25 times better performance via `getElementsBy*`, which is O(c) - compared to best-case `querySelectorAll` O(n).
For some cases that can reduce `queryAll` complexity from O(rules * nodes) to O(rules * c).

**Comment by josh** [comment]
I did originally try that approach years and years ago when this was originally authored. But the compound selector did perform better. That said, browser engines have changed a lot since then so things may have changed.

This project is basically in maintenance mode after 6 years. I can't commit to making big algorithm changes at this point without a lot of testing.

Thanks,
Josh
